### ISSUE TITLE
Can't be compiled for CTRUlib v1.0.0

### ISSUE THREAD

**Issue by d0k3** [Steveice10/ctrcommon#6]
Are there plans to update this for CTRUlib 1.0.0? If not I guess I'll switch to Citrus or see if I can do without an additional library.

**Comment by Steveice10** [comment]
I suppose I can take care of this shortly.

**Comment by hartmannaf** [comment]
I modified it to compile my FreeMultiPatcher, I could create a pull request for my changes.

**Comment by Steveice10** [comment]
Done.

**Comment by d0k3** [comment]
Thanks, both of you! Hoping to get my CTRXplorer up and running again, soon. I suppose for long term support it may be better to switch to Citrus, right?

**Comment by Steveice10** [comment]
I definitely plan to support citrus more, as it's basically "ctrcommon 2.0", but I will try to keep ctrcommon working if people still use it.

**Comment by hartmannaf** [comment]
You forgot to update makerom, and the gspgpuEvents need to stay gspEvents like before to work.

Also do you have any tipps to move over to citrus, since a would like to port my FreeMultiPatcher to use citra in the future.

**Comment by d0k3** [comment]
I see that's already fixed, thank you again! 

On migrating to Citrus, I've been pondering that for a time. Basically, Citrus seems to contain one to one alternatives of most functions in ctrcommon (they are just called differently and the interface might differ slightly). Also, some highly specific UI functions are no more included in Citrus - it is unlikely you used them anyways. 

I guess a good starting point would be FBI, there's a specific commit that replaced ctrcommon with Citrus.

**Comment by Steveice10** [comment]
Yeah, the UI code devolved into a bit of a mess of arguments and what not over time, so I decided to exclude it from citrus. I just lumped it in with the FBI code, since that was my only project that used it.

**Comment by d0k3** [comment]
Sorry to bother you again, but I've now installed this... this is what I get when I'm using the base Makefile:
linking CTRXplorer.elf
built ... CTRXplorer.3dsx
built ... CTRXplorer.smdh
[RSF ERROR] Unrecognised Key: 'ExeFs'
[RSF ERROR] Error Proccessing RSF file
built ... CTRXplorer.3ds
[RSF ERROR] Unrecognised Key: 'ExeFs'
[RSF ERROR] Error Proccessing RSF file
built ... CTRXplorer.cia
built ... CTRXplorer.zip

I'm already working on migrating my code over to Citrus, guess that will be the best option in the long run.
